apiVersion: apps/v1
kind: Deployment
metadata:
  name: smario-deployment
spec:
  selector:
    matchLabels:
      app: mario
  replicas: 1 
  template:
    metadata:
      labels:
        app: mario
    spec:
      containers:
      - name: mario
        image: bharathshetty4/supermario:latest
        ports:
        - containerPort: 8080  
 
 # cuando docker hub esta excedido... se puede usar .... pengbai/docker-supermario
        
        
