#! clu_ytt yaml

#@ load("@ytt:data", "data")


apiVersion: run.tanzu.vmware.com/v1alpha3
kind: TanzuKubernetesCluster
metadata:
  name: #@ data.values.cluName
spec:
  settings:
    storage:
      defaultClass: #@ data.values.defStoreClass
  topology:
    controlPlane:
      replicas: #@ data.values.ctrlRepl
      storageClass: #@ data.values.defStoreClass
      tkr:
        reference:
          name: #@ data.values.tkr
      vmClass: #@ data.values.vmClassSmall
      volumes:
      - capacity:
          storage: 4Gi
        mountPath: /var/lib/etcd
        name: etcd
    nodePools:
    - name: worker-np
      replicas: #@ data.values.workRepl
      storageClass: #@ data.values.defStoreClass
      tkr:
        reference:
          name: #@ data.values.tkr
      vmClass: #@ data.values.vmClassMedium
      volumes:
      - capacity:
          storage: 50Gi
        mountPath: /var/lib/containerd
        name: containerd
      - capacity:
          storage: 50Gi
        mountPath: /var/lib/kubelet
        name: kubelet
