apiVersion: run.tanzu.vmware.com/v1alpha3
kind: TanzuKubernetesCluster
metadata:
  name: tkg-cluster-01 #name of cluster
  namespace: grupo1 #name of namespace
  annotations: run.tanzu.vmware.com/resolve-os-image: os-name=ubuntu
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-xlarge 
      storageClass: vc01cl01-t0compute
      volumes:
        - name: etcd
          mountPath: /var/lib/etcd
          capacity:
            storage: 4Gi      
      tkr:                                       
        reference:
          # name: v1.21.2---vmware.1-tkg.1.ee25d55
          name: v1.23.8---vmware.3-tkg.1
    nodePools:
    - name: worker-nodepool-a1  
      replicas: 1
      vmClass: best-effort-xlarge 
      storageClass: vc01cl01-t0compute
      volumes:
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 16Gi
        - name: kubelet
          mountPath: /var/lib/kubelet
          capacity:
            storage: 16Gi
      tkr:  
        reference:
          name: v1.23.8---vmware.3-tkg.1     
  settings:
    storage:
      defaultClass: vc01cl01-t0compute
    network:
      cni:
        name: calico # antrea / antrea-nsx-routed      
      services:
        cidrBlocks: ["198.51.100.0/12"]
      pods:
        cidrBlocks: ["192.0.2.0/16"]
#   trust:
#     additionalTrustedCAs:
#       - name: harbor
#         data: LS0tLS1C...LS0tCg==  

# https://docs.vmware.com/en/VMware-vSphere/8.0/vsphere-with-tanzu-tkg/GUID-D09930F7-9EC9-40D5-9349-4FC49E9EA5FB.html
