apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: http-ingress
  namespace: test-ingress
  labels:
    app: hello
spec:
  virtualhost:
     fqdn: foo.bar.com
  routes:
    - conditions:
      - prefix: /
      services:  
        - name: s1
          port: 80
          weight: 30
        - name: s2a
          port: 80
          weight: 70
