apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: podinfo-ingress
  namespace: test
spec:
  virtualhost:
    fqdn: app.foo.bar.com
  includes:
    - name: podinfo
      namespace: test
      conditions:
        - prefix: /
