apiVersion: v1 
kind: Service 
metadata: 
  name: podinfo-svc
  namespace: test
  labels:
    app: podinfo
spec: 
  selector: 
    app: podinfo
  ports: 
    - port: 9898
      targetPort: 9898

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: podinfo-ingress
  namespace: test
  labels:
     app: podinfo
spec:
  rules:
  - host: app.foo.bar.com
    http:
      paths:
      - path: /
        backend:
          serviceName: podinfo-svc
          servicePort: 9898



