apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
  namespace: nginx
spec:
  containers:
  - image: nginx
    name: docker.io/bitnami/nginx:1.23.1-debian-11-r0
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
