apiVersion: v1 

kind: Service 

metadata: 

  name: mssql-deployment 

spec: 

  selector: 

    app: mssql 

  ports: 

    - protocol: TCP 

      port: 1433 

      targetPort: 1433 

      # nodePort: 30002

      # port: 22

      # targetPort: 22

 

  type: LoadBalancer 
